
abbr_dict={
    
    "CC" : "Carbon-copy. Works the same way as email",
    "CX" : "Correction",
    "CT" : "Cuttweet. Another way of saying partial retweet",
    "DM" : "Direct message. A direct-message is a message only you and the person who sent it can read",
    "HT" : "Hat tip. This is a way of attributing a link to another Twitter user",
    "MT" : "Modified tweet. This means the tweet you're looking at is a paraphrase of a tweet originally written by someone else",
    "PRT" : "Partial retweet. The tweet you're looking at is the truncated version of someone else's tweet",
    "PRT" : "Please retweet, a plea to put at the end of a tweet",
    "RT" : "Retweet",
    "EM" : "Email Marketing",
    "EZine" : "Electronic Magazine",
    "FB" : "Facebook",
    "LI" : "LinkedIn",
    "SEO" : "Search Engine Optimization",
    "SM" : "Social Media",
    "SMM" : "Social Media Marketing",
    "SMO" : "Social Media Optimization",
    "SN" : "Social Network",
    "SROI" : "Social Return on Investment",
    "UGC" : "User Generated Content",
    "YT" : "YouTube",
    "#" : "start to a hashtag, or a way of organizing subjects on Twitter",
    "AB/ABT" : "About",
    "AFAIK" : "As far as I know",
    "AYFKMWTS" : "Are you f---ing kidding me with this s---?",
    "B4" : "Before",
    "BFN" : "Bye for now",
    "BGD" : "Background",
    "BH" : "Blockhead",
    "BR" : "Best regards",
    "BTW" : "By the way",
    "CD9" : "parents are around",
    "CHK" : "Check",
    "CUL8R" : "See you later",
    "DAM" : "Don't annoy me",
    "DD" : "Dear daughter",
    "DF" : "Dear fiancé",
    "DP" : "used to mean profile pic",
    "DS" : "Dear son",
    "DYK" : "Did you know, Do you know",
    "EM/EML" : "Email",
    "EMA" : "Email address",
    "F2F" : "Face to face",
    "FF" : "Follow Friday",
    "FOTD" : "Find of the day",
    "FTW" : "For the win, F--- the world",
    "FUBAR" : "F---ed up beyond all repair",
    "FWIW" : "For what it's worth",
    "GTS" : "Guess the song",
    "HAGN" : "Have a good night",
    "HAND" : "Have a nice day",
    "HOTD" : "Headline of the day",
    "HT" : "Heard through",
    "HTH" : "Hope that helps",
    "IC" : "I see",
    "ICYMI" : "In case you missed it, a quick way to apologize for retweeting your own material",
    "IDK" : "I don't know",
    "IIRC" : "If I remember correctly",
    "IMHO" : "In my humble opinion",
    "IRL" : "In real life",
    "IWSN" : "I want sex now",
    "JK" : "Just kidding, joke",
    "JSYK" : "Just so you know",
    "JV" : "Joint venture",
    "KK" : "Kewl kewl, or ok, got it",
    "KYSO" : "Knock your socks off",
    "LHH" : "Laugh hella hard (stronger version of LOL)",
    "LMAO" : "Laughing my ass off",
    "LMK" : "Let me know",
    "LO" : "Little One (child)",
    "LOL" : "Laugh out loud",
    "MM" : "Music Monday",
    "MIRL" : "Meet in real life",
    "MRJN" : "Marijuana",
    "NBD" : "No big deal",
    "NCT" : "Nobody cares, though",
    "NJoy" : "Enjoy",
    "NSFW" : "Not safe for work",
    "NTS" : "Note to self",
    "OH" : "Overheard",
    "OOMF" : "One of my friends/followers",
    "ORLY" : "Oh, really?",
    "PLMK" : "Please let me know",
    "PNP" : "Party and Play (drugs and sex)",
    "QOTD" : "quote of the day",
    "RE" : "In reply to, in regards to",
    "RLRT" : "Real-life re-tweet, a close cousin to OH",
    "RTQ" : "Read the question",
    "SFW" : "Safe for work",
    "SMDH" : "Shaking my damn head, SMH, only more so",
    "SMH" : "Shaking my head",
    "SNAFU" : "Situation normal, all f---ed up (slang from the US Military)",
    "SO" : "Significant Other",
    "SRS" : "Serious",
    "TFTF" : "Thanks for the follow",
    "TFTT" : "Thanks for this tweet",
    "TJ" : "Tweetjack, or joining a conversation belatedly to contribute to a tangent",
    "TL" : "Timeline",
    "TMB" : "Tweet me back",
    "TT" : "Trending topic",
    "TY" : "Thank you",
    "TYIA" : "Thank you in advance",
    "TYT" : "Take your time",
    "TYVW" : "Thank you very much",
    "W" : "With",
    "WE" : "Whatever or weekend",
    "WTV" : "Whatever",
    "YGTR" : "You got that right",
    "YKWIM" : "You know what I mean",
    "YKYAT" : "You know you're addicted to",
    "YMMV" : "Your mileage may vary",
    "YOLO" : "You only live once",
    "YOYO" : "You're on your own",
    "YW" : "You are welcome",
    "ZOMG" : "OMG to the max",
    "BrandChat" : "private chat about branding",
    "CMAD" : "Community Manager Appreciation Day",
    "CMGR" : "Community Manger topic chat",
    "FB" : "The user is sending this post to Facebook",
    "FF" : "Short way of saying Follow Friday, or a recommendation that others follow the user",
    "in" : "the user is sending this post to LinkedIn",

    "gopdebate": "republican party presidential",
    "gop": "republican party presidential",

}